diwic/alsa-rs

- src/poll.rs
because of updates of libc and bitflags, these two changes were needed to make the lib compile
> fix compilation errors because of updated dependencies

- src/mixer.rs
This will fix some compilation errors on 32 bit systems (raspberry pi)
> use libc types to fix compilation on 32bit arm (rpi)

- src/mixer.rs
I needed to be able to unmute line-in. It was missing from selem struct.
> add capture and playback switches

- src/lib.rs
- src/mixer.rs
I've added [snd_mixer_selem_set_playback_dB](http://www.alsa-project.org/alsa-doc/alsa-lib/group___simple_mixer.html#ga8bfb52575e4bb06deb30799bc39c0768)
This function uses `dir` to `select direction (-1 = accurate or first bellow, 0 = accurate, 1 = accurate or first above)`. I've added an enum for this called `AccuracyDirection` but there is also a `ValueOr` enum in `lib.rs`. Should I use ValueOr for this function too?
> add setting volume in decibel

- synth-example/src/main.rs
My Miditech MIDI controller sends Noteon events with the velocity set to
0 instead of sending the Noteoff event. This change makes the synth
behave as expected.
> Silence note on Noteon event with 0 velocity.

- src/device_name.rs
Just a convenience thing. I hope temporarily creating a `CString` (and unwrapping it) just for a single function call is not against the lib's philosophy. 
I'm not particularly happy with the function's name, any suggestions?
> Add a constructor with &str argument for HintIter

- Cargo.toml
- src/error.rs
- src/pcm_direct.rs
`PTRACE_GETFPXREGS` and `PTRACE_SETFPXREGS` were removed in https://github.com/rust-lang/libc/commit/d2695436ba5072078796c76f727a296e0f43caa6 and thus `nix` was failing to compile for arm targets if some other crate depended on `libc: ^0.2.55` and above. 
The fix for `nix` (https://github.com/nix-rust/nix/commit/196b05b5c7be39b73dcadca5457948d807fdf913) was backported but only down to `0.11` (https://github.com/nix-rust/nix/issues/1057) 
I have not yet run the test cases on this yet, currently on a windoze machine, will try doing them tomorrow. 
Do you foresee any issues?
> Bump nix and libc to fix arm compilation issues 

- src/mixer.rs
I'm not sure about catching events api,
but anyway i guess functions like snd_mixer_handle_events and/or snd_hctl_handle_events should be wrapped even using poll.
> add handle_events to mixer api

- src/poll.rs
`nfds_t` is `unsigned int` on Android, DragonFly, FreeBSD, NetBSD all of which can use ALSA. See https://github.com/rust-lang/libc/search?q=nfds_t
> Unbreak build on BSDs

- src/rawmidi.rs
Attempting to use non-blocking IO on an input device in rawmidi causes an assert in libasound:
midirust: rawmidi_hw.c:213: snd_rawmidi_hw_open: Assertion `outputp' failed.
This seems to be because we are passing SND_RAWMIDI_APPEND (1) instead of SND_RAWMIDI_NONBLOCK (2) into rawmidi_open and there is no output device.
This patch would be better if it had the proper constants in, of course, but this fixes it for the time-being.
> rawmidi: Fix non-blocking open on input devices

- src/device_name.rs
- src/direct/pcm.rs
Just two things caught by clippy:
- [`clippy::eq_op`](https://rust-lang.github.io/rust-clippy/master/#eq_op)
- [`clippy::temporary_cstring_as_ptr`](https://rust-lang.github.io/rust-clippy/master/#temporary_cstring_as_ptr)
> Fix clippy warnings (deny by default)

- src/pcm.rs
This is useful for determining the instant at which the currently
buffered samples will have completed playback.
> Expose `snd_pcm_delay`

- src/poll.rs
So library users don't have to put libc in their Cargo.toml in order to for example store pollfd's in a struct (or otherwise pass around pollfd's explicitly).
> Re-export libc::pollfd

- synth-example/Cargo.toml
Clap is not used/mentioned anywhere in the example
> Remove clap from synth-example

- Cargo.toml
Hi,
could you please update the nix version used, and also `cargo publish` to crates.io, as the nix version there is quite old (0.15).
Thank you
> update nix to 0.20

- synth-example/Cargo.toml
I've tried to run synth example locally, and it failed to resolve dependency.
```bash
pi@raspberrypi:~/projects/alsa-rs/synth-example $ cargo run 
Updating crates.io index
error: failed to select a version for the requirement `alsa = "^0.4"`
candidate versions found which didn't match: 0.5.0
location searched: /home/pi/projects/alsa-rs
required by package `synth-example v0.1.0 (~/projects/alsa-rs/synth-example)`
```
Fixing it to `0.5` solves the problem (and introduces new one 😆)
> Update Cargo.toml to match root package version

- src/seq.rs
This PR removes a superfluous backtick character from a doc comment that broke markdown rendering in rustdoc.
> seq: Fix broken markdown syntax

- synth-example/Cargo.toml
- synth-example/src/main.rs
Hello!
I've noticed that after version `0.6` release the `synth-example` had `alsa-rs` pinned to version `0.5`. Fixed that along with a minor API change that broke the synth build.
> Fix example synth

- src/hctl.rs
This is similar to #48, adding snd_hctl_handle_events to Hctl to make Hctl::wait actually useful.
> add handle_events to hctl api

- src/mixer.rs
I wanted to be able to use consistent values for getting and setting volume, which I discovered can be done by setting the range for these. So I implemented snd_mixer_selem_set_playback_volume_range and snd_mixer_selem_set_capture_volume_range for Selem.
> add set_playback_volume_range and set_capture_volume_range to Selem

- src/pcm.rs
Useful for getting an accurate String representation for logs and for programmatically writing config files.
> impl fmt::Display for Format

- src/ctl_int.rs
Necessary to actually get/set values for a given elem. Tested on amd64 and aarch64.
> implement read/write from ElemValue

- src/lib.rs
- src/pcm.rs
I tried to do this in a similar way to existing code. I just did the functions I needed; if you would prefer to have all format functions from https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___helpers.html implemented at once I can look at doing that.
> Add functions to pcm::Format to get various attributes

- src/mixer.rs
* Implement `set_capture_volume_all`, `ask_playback_db_vol`, and `ask_capture_db_vol` for Selem.
* Fix return value os `Mixer::wait`. The return value of the inner `snd_mixer_wait` should be tested against zero (success) instead of one.
> Implement new methods for Selem and fix return value of Mixer::wait

- examples/enumerate.rs
- src/ctl_int.rs
- src/lib.rs
- src/pcm.rs
This PR adds a couple of methods that make it easier to list hardware devices and their subdevices.
The additional methods on the `Info` wrapper make it possible to prepare it in order to get it updated via the new `info` method on the `Ctl`. 
Additionally, the new `pcm_next_device` on `Ctl` is needed to get the device numbers for a card.
> Add methods useful for device/subdevice listing

- Cargo.toml
Bump up nix to 0.27 to resolve compile issues for new targets (LoongArch/RISC-V).
> Update nix to 0.27

- Cargo.toml
- src/direct/ffi.rs
There was an off-by-one error (13 instead of 14) for the SIZEBITS value that caused the ioctl code to be screwed up. 
Resolves: #118
> Fix ioctl bug on linux

- src/chmap.rs
These four positions were missing in the rust definition of the enum. No idea why. However, that made it impossible to construct any standard surround channel map (which need rear-right (4.0 onward), LFE (2.1 onward), front-center (5.0 onward), or side-left (7.1 onward)).
> Add missing chmap positions

- examples/ctl_list.rs
- src/ctl_int.rs
- src/lib.rs
This allows enumerating control values on a device.
> Add ElemList
